### ISSUE TITLE
Uitbreiding Documentfunctionaiteit

### ISSUE THREAD

**Issue by rutger-h** [generiekzaakafhandelcomponent/gzac-issues#24]
# Doel
Het zorgen dat het werken met grotere aantallen (100+) documenten prettig werkt voor gebruikers en voldoet aan de eisen van Amsterdam NISE, Utrecht VCG en Den Haag SZW. 

# Context / achtergrond
GZAC ondersteunt een subset van de VNG Realisatie ZGW standaard [Documenten API](https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/). De API ondersteunt het opslaan en naar andere applicaties ontsluiten van informatieobjecten (in de ‘volksmond’: documenten). De component slaat deze gestructureerd en voorzien van de benodigde metadata op en stelt applicaties in staat deze te wijzigen, te verwijderen en aan de hand van een aantal zoekcriteria op te vragen.

De API is een standaard, geen software. Het voordeel is dat systemen die deze API onderstandaard ondersteunen, uitwisselbaar zijn. 

# Huidige situatie GZAC
De documenten (formeel "zaakinformatieobjecten") die worden gebruikt bij een zaakdossier worden opgeslagen via de Documenten API. De daadwerkelijke fysieke locatie van documenten ligt daarmee in laag 1, en is afhankelijk van de keuze van de Documenten API. Dit kan bijvoorbeeld een schijf (_persistent storage_) of DMS zijn. 

Bij upload van nieuwe documenten worden deze voorzien van meta-data. Dit is te zien in de tab 'Documenten' bij een zaakdossier. De documenten die worden geupload, worden voorzien van meta-data.

![Screenshot 2023-11-01 at 14 49 14](https://github.com/generiekzaakafhandelcomponent/roadmap-items/assets/59374585/10478921-3818-4523-b493-f377c6e241b6)

De lijstweergave van documenten biedt op dit moment zeer beperkt meta-informatie over documenten, die over het algemeen niet heel bruikbaar is (attributen grootte, filenaam). De meta-informatie die wordt toegevoegd bij de upload wordt niet getoond in de lijstweergave. Er kan niet worden gefilterd en/of gesorteerd, en de Document API meta-data is niet zichtbaar. 

<img width="1213" alt="Screenshot 2023-09-25 at 13 13 54" src="https://github.com/generiekzaakafhandelcomponent/roadmap-items/assets/59374585/04d19d8a-f244-4025-9b3d-b2bfdb99733e">

Om te kunnen werken met grotere sets aan files is meer functionaliteit nodig. Gesproken wordt over een 'mappen structuur' - dit is lastig te bereiken met de Documenten API standaard, maar het illustreert de achterliggende wens. 

# Uitgangspunten
1. GZAC werkt met elk DMS dat de Documenten API ondersteunt.
2. GZAC is gebouwd rondom het concept Case management / Zaakgericht werken. Het doel is
de applicatie alleen dit te laten doen, en niet te laten uitgroeien tot een monolithische silo-
applicatie die ‘all-in-one’ biedt.

# Wat moet er gebeuren - wat is er nog niet en hebben we wel nodig?

1. Carbon lijstscherm.
2. De meta-data uit de Documenten API moet getoond worden in de kolommen.
3. De meta-data uit de Documenten API moet door een user gewijzigd kunnen worden.
4. Welke kolommen in de lijst getoond worden (aan/uit) en de volgorde is instelbaar via
dossier-management pagina.
5. In het dossiermenu wordt per zaakdossiertype een lijst van trefwoorden vastgelegd, die
gebruikt kunnen worden bij upload van files.
6. Bij het uploaden van een file worden bij de bestaande meta-data ook trefwoord-keuze
opgenomen (keuze uit de lijst vastgesteld onder 5). Deze wordt vastgelegd in de
Documenten API.
6a. De meta-data die in de al bestaande upload wordt vastgelegd, blijft bestaan. (het 1ste screenshot vanuit Den Haag geeft dit weer, het 4de screenshot van de UX van de upload is niet correct ontworpen). 
7. Er kan worden gefilterd op alle meta-data. Voorbeeld: alleen documenten van het type PDF
met trefwoord Bouwtekening.
8. Welke filters (search fields) voor de gebruiker beschikbaar zijn (aan/uit) en de volgorde is instelbaar via
dossier-management pagina.
9. Word en PDF documenten openen standaard in een preview in de browser (en worden dus
niet gedownload).
10. Er is een aparte knop voor downloaden van 1 document per stuk.
11. Er is een aparte knop voor het verwijderen van 1 documenten per stuk.
12. Documenten standaard gesorteerd op volgorde van aanmaak (binnenkomst) naar de minst recente documenten onderaan.
13. De lijst van documenten is per kolom te sorteren. 
14. De functies worden ontwikkeld op versie 1.4.3 van de Documenten API én er wordt indien mogelijk voorzien in een mechanisme om meerdere toekomstige versies naast elkaar te ondersteunen voor zover haalbaar. 
15. Ondersteuning voor Documenttype (CV, Besluit, Bijlage bij aanvraag, Uitnodigingsbrief, etc..), formeel https://www.gemmaonline.nl/index.php/Imztc_2.2/doc/objecttype/informatieobjecttype.

# Visualisatie van gewenste functionaliteit

![Screenshot 2023-09-28 at 15 27 13](https://github.com/generiekzaakafhandelcomponent/roadmap-items/assets/59374585/3393c613-ce74-4895-968b-05fbcca07354)
![Screenshot 2023-09-28 at 15 27 37](https://github.com/generiekzaakafhandelcomponent/roadmap-items/assets/59374585/b26febcb-5895-4d46-9f14-5a54ae6ad86c)
![Screenshot 2023-09-28 at 15 27 24](https://github.com/generiekzaakafhandelcomponent/roadmap-items/assets/59374585/bf1e4d37-5e71-4649-8801-ab29eb817498)
![Screenshot 2023-09-28 at 15 27 46](https://github.com/generiekzaakafhandelcomponent/roadmap-items/assets/59374585/a15fd95c-4218-42bf-ad80-58a3786c6c7b)

# Wat valt er buiten scope?
1. Het opknippen van zeer grote bestanden in delen.
2. Het ondersteunen van Documenten die niet aan een zaak zijn gekoppeld.
3. Printen.
4. Zoeken in documenten.
5. Zoeken via documenten. Dus, documenten hangen onder een zaakdossier, en worden op die
manier gevonden. Er is geen losse ‘documenten-ingang’ voorzien.
6. Versionering van documenten.

**Impact - hoeveel inspanning kost dit?**
Inschatting door PO: L
Inschatting door SA: S/M/L/XL

**Comment by rmaijers** [comment]
@rutger-h na.v. bespreking binnen Ams daarnet:
 Punt 6 verwijst naar ' lijst vastgesteld onder 3', dat moet zijn ' lijst vastgesteld onder 5'?
En punt 4 omvat punt 14.

**Comment by rutger-h** [comment]
@rmaijers : dank, beiden verwerkt. De verwijzing is nu naar 5 en punt 14 verwijderd wegens duplicaat.

**Comment by JanBrek** [comment]
Ik neem aan dat het genoemde 'trefwoord' de trefwoord functie is bij een informatieobject in de Documenten API right?
Let dan even op dat je vast zit aan Documenten API >= v1.3

**Comment by rutger-h** [comment]
@JanBrek : ja. En ik heb direct een punt toegevoegd: "De functies worden ontwikkeld op versie 1.4.3 van de Documenten API én er wordt indien mogelijk voorzien in een mechanisme om meerdere toekomstige versies naast elkaar te ondersteunen voor zover haalbaar." Eens?

**Comment by ThomasMinkeRitense** [comment]
> Ik neem aan dat het genoemde 'trefwoord' de trefwoord functie is bij een informatieobject in de Documenten API right? Let dan even op dat je vast zit aan Documenten API >= v1.3

Dank Jan! 1.4 zelfs, in Open Zaak 1.10.
https://github.com/VNG-Realisatie/documenten-api/blob/master/CHANGELOG.rst
https://open-zaak.readthedocs.io/en/stable/development/changelog.html

**Comment by JanBrek** [comment]
@ThomasMinkeRitense  Hmm die documentatie klopt niet dan. Ik zag hem er nl bij 1.3 al bij staan :)
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/catalogi-api/1.3.0/src/openapi.yaml#/informatieobjecttypen/informatieobjecttype_update

In ieder geval goed dat het in OpenZaak 1.10 gebruikt kan worden omdat ze daar 1.3 gaan supporten :)

@rutger-h Is het wel slim om het tegen 1.4.3 te ontwikkelen? Ik weet zelf niet de roadmap van OpenZaak, en in theorie zou dat jullie niet mogen blokkeren denk ik, maar praktisch gezien misschien de laagst mogelijke versie vast zetten zodat zo veel mogelijk gemeenten dit kunnen gebruiken? (Dus met een 'oudere' OpenZaak en/of VNG specificatie)

**Comment by rutger-h** [comment]
@JanBrek : gewetensvraag idd. De strategie is latest over het algemeen, maar de verschillen lijken niet groot, dus we kunnen een stukje terug gaan in de versies. Laten we het team om advies vragen.

**Comment by AntonVissers** [comment]
In het schermvoorbeeld van de upload is er alleen ruimte voor een titel, beschrijving en trefwoorden. 
Ik mis de mogelijkheid om de overige metadata te beïnvloeden

- Status,  deze is van belang voor de zichtbaarheid in het klantportaal en mogelijk in de toekomst voor het al dan niet wijzigen van documenten
- Beveiligingsniveau. Soms is het noodzakelijk om van de standaard instelling voor de zaak af te wijken. Denk bijvoorbeeld aan medische documenten die niet voor iedereen met toegang tot de zaak zichtbaar mogen zijn.

Is er voorzien in het wijzigen van de metadata van documenten in een dossier?

**Comment by rutger-h** [comment]
> In het schermvoorbeeld van de upload is er alleen ruimte voor een titel, beschrijving en trefwoorden. Ik mis de mogelijkheid om de overige metadata te beïnvloeden
> 
> * Status,  deze is van belang voor de zichtbaarheid in het klantportaal en mogelijk in de toekomst voor het al dan niet wijzigen van documenten
> * Beveiligingsniveau. Soms is het noodzakelijk om van de standaard instelling voor de zaak af te wijken. Denk bijvoorbeeld aan medische documenten die niet voor iedereen met toegang tot de zaak zichtbaar mogen zijn.
> 
> Is er voorzien in het wijzigen van de metadata van documenten in een dossier?

Dank - ik heb punt 6a toegevoegd. De UX van de upload is inderdaad niet correct, die suggereert dat er maar een deel van de meta-data wordt opgevraagd, dit moet uiteraard alles zijn dat wordt vastgelegd. Twee: er is twijfel over de haalbaarheid van upload van meerdere documenten en het vastleggen van meta-data daarvan. Er komt een aanpassing van de concept UX, wordt voorgelegd.

**Comment by rutger-h** [comment]
> Is er voorzien in het wijzigen van de metadata van documenten in een dossier?

Nee. Mag dat buiten MVP wat jullie betreft?

**Comment by erwinvdh** [comment]
> > Is er voorzien in het wijzigen van de metadata van documenten in een dossier?
> 
> Nee. Mag dat buiten MVP wat jullie betreft?

Uit eerder gesprekken met Den Haag heb ik begrepen dat het kunnen wijzigen van metadata van documenten door de user wel gewenst is. Is het mogelijk om deze requirement toch mee te nemen binnen de scope van het MVP? (het staat overigens ook als punt 3 genoemd onder 'Wat moet er gebeuren - wat is er nog niet en hebben we wel nodig?'

**Comment by StijnBoots** [comment]
Eens met @erwinvdh, niet alle documenten worden handmatig ge-upload en kunnen door een fout in de aanlevering nog wel eens verkeerd geclassificeerd binnenkomen. Een snelle aanpassing binnen GZAC is dan erg prettig in tegenstelling tot het opnieuw moeten uitvoeren van een upload.

**Comment by rutger-h** [comment]
Nav input Bastiaan en Richard punt 15 opgenomen, ondersteuning Document type.

**Comment by joeribekker** [comment]
Als ik dit zo lees, haal ik hier de volgende aanpassingen uit voor de Documenten API:

Tags is in deze user story een soort container begrip voor zo'n beetje alles (bestandstype, informatieobjecttype). Dat is een functionele invulling en behoeft volgens mij dan geen technische invulling (op basis van wat ik hier lees).

> 7. Er kan worden gefilterd op alle meta-data. Voorbeeld: alleen documenten van het type PDF met trefwoord Bouwtekening.

In combinatie met de screenshot, zouden er dus query parameters toegevoegd moeten worden aan de documenten lijst endpoint (`/enkelvoudiginformatieobjecten`), te weten:

* `bestandstype` -- Hiervoor moeten we dit veld toevoegen. Dat kan alleen lezen zijn, en bepaald worden op basis van wat er achter de laatste `.` staat. Je zou eventueel ook `formaat` kunnen gebruiken als query parameter.
* `auteur` -- Dit zal dan partial matches, case insensitive worden.
* `beschrijving` -- Dit zal dan partial matches, case insensitive worden.
* `bestandsgrootte` -- Deze zou ik weglaten. Ga je echt zoeken op bestandsgrootte? Of, geen alle bestanden groter dan 5 MB?
* `aanmaakdatum__gte` en * `aanmaakdatum__lte` zodat je in periodes kan zoeken, of oude kan weglaten (gte=greater than or equal, lte=lesse than or equal)

Zelf zou ik dan meteen toevoegen:

* `titel` -- Dit zal dan partial matches, case insensitive worden.
* `vertrouwelijkheidaanduiding` -- enum dus exact match
* `trefwoorden` -- OF- of EN-combinatie van trefwoorden, exact of partial... weet ik niet zo goed wat handig is.
* `lock` -- Wellicht kunnen filteren welke bestanden zijn gelockt (ofwel, die in gebruik zijn).

Het lijkt me essentieel om dit asap te gaan verwerken in de Documenten API.

> 12. De lijst van documenten is per kolom te sorteren.

Dit is een lastige omdat punt 4 zegt dat je in de UI wil kunnen kiezen uit welke kolommen er weergegeven moeten worden. Dit impliceert dat je eigenlijk op alles wilt kunnen sorteren. Dit lijkt me dan echter weer niet zo nuttig dus laten we de nuttige kolommen doen en niet alles :) 

Op basis van de screenshot stel ik voor, te kunnen sorteren -zowel asc als desc- op: 

* `titel` -- Prima.
* `bestandstype` -- Lijkt me niet zo nuttig maar het kan.
* `beschrijving` -- Lijkt me niet van toepassing, zou ook niet weten hoe precies.
* `omvang` -- Prima.
* `aanmaakdatum` -- Prima.
* `auteur` -- Prima

Verder lijken me er geen nuttige attributen in te zitten. Ook deze lijken me goed om asap te verwerken.

Vraag: Kunnen jullie feedback geven op mijn voorstel om dit aan de kant van de Documenten API toe te gaan voegen?

**Comment by JanBrek** [comment]
Ziet er goed uit!
Ik zou de vertrouwelijkheidaanduiding filter wel multi-select maken als je dat niet al bedoelde. Zodat je bijv. de hoogste vertrouwelijkheid er uit kan filteren

**Comment by ThomasMinkeRitense** [comment]
Dank voor je voorstel @joeribekker!

> Tags is in deze user story een soort container begrip voor zo'n beetje alles (bestandstype, informatieobjecttype)
- voor zover ik kan zien is tags in deze user story direct gekoppeld aan trefwoorden. Geen aanpassingen nodig.
> Hiervoor moeten we dit veld toevoegen. Dat kan alleen lezen zijn, en bepaald worden op basis van wat er achter de laatste . staat. Je zou eventueel ook formaat kunnen gebruiken als query parameter.
- Volgens mij moeten we hiervoor gewoon het formaat veld gebruiken
> Deze zou ik weglaten. Ga je echt zoeken op bestandsgrootte? Of, geen alle bestanden groter dan 5 MB?
- Het plaatje is een impressie. Ik denk dat niemand deze zou gebruiken, dus eens om hem niet mee te nemen
> trefwoorden -- OF- of EN-combinatie van trefwoorden, exact of partial... weet ik niet zo goed wat handig is.
- Ik denk OF & exact. Maar misschien kun je de of/en ook zelf meegeven?
> Dit is een lastige omdat punt 4 zegt dat je in de UI wil kunnen kiezen uit welke kolommen er weergegeven moeten worden. Dit impliceert dat je eigenlijk op alles wilt kunnen sorteren.
- Deze klopt denk ik niet helemaal. Het feit dat bepaalde kolommen getoond worden in de lijst betekent niet direct dat ze sorteerbaar moeten zijn
> Op basis van de screenshot stel ik voor, te kunnen sorteren -zowel asc als desc- op:
- Ik zou zeggen: beschrijving eruit. Ik denk zelf nog aan vertrouwelijkheidsaanduiding en status, maar ik kan niet goed inschatten of dat nuttig is

Last but not least: 
- We zoeken voor deze lijst altijd Documenten in die gekoppeld zijn aan een Zaak. Eigenlijk hebben we bovenstaande filters en sortering dus nodig op het /zaakinformatieobjecten endpoint in plaats van op de /enkelvoudiginformatieobjecten. De andere optie is om aan /enkelvoudiginformatieobjecten ook een filter op de zaak te bouwen. Wat zijn hier de mogelijkheden in?
- Ik zou heel graag een paginated list willen laten zien in GZAC. Kunnen we ook, ofwel op het /enkelvoudiginformatieobjecten (met zaak-filter) of op /zaakinformatieobjecten (met alle bovengenoemde filters) pagination inbouwen?

**Comment by joeribekker** [comment]
> /enkelvoudiginformatieobjecten ook een filter op de zaak te bouwen. 

Bizar dat die er niet in zit. Moet er bij 

> Ik zou heel graag een paginated

Is al zo?

**Comment by ThomasMinkeRitense** [comment]
Ik zie inderdaad dat die al in /enkelvoudiginformatieobjecten zit. 

Een ander punt: als zowel de Zaken API als de Documenten API van Open Zaak gebruikt worden lijkt het me geen probleem om een zaken-filter op /enkelvoudiginformatieobjecten te zetten. We hebben alleen niets aan die filter als er een ander DMS wordt gebruikt met de CMIS adapter. Als we alle bovengenoemde filtering en sortering opties toevoegen (en pagination) aan  /zaakinformatieobjecten, zou dit tweede scenario dan ook werken?

**Comment by joeribekker** [comment]
Je kan gewoon filteren op zaak-url, deze is bekend in de documenten API dus ook via CMIS.

Echter, CMIS ondersteuning hebben we on hold gezet sinds 1.9. Er waren geen stakeholders voor en DMS leveranciers nemen het niet zo nauw met de CMIS standaard dus altijd issues.

**Comment by ThomasMinkeRitense** [comment]
Hoe werkt dat met de zaak-url in de Documenten API? Als de Zaken API en de Documenten API twee verschillende componenten zijn, dan weet een Document toch niet aan welke Zaak het gekoppeld is?

**Comment by joeribekker** [comment]
De object-informatieobject (oio) in de Documenten API heeft die gewoon. Is een verwijzing net zoals je van zaak naar object kan verwijzen.

**Comment by ThomasMinkeRitense** [comment]
Mooi, die is nieuw voor mij. Volgens mij hebben we dan alles wat we nodig hebben.

**Comment by joeribekker** [comment]
Ticket aangepast nav alle comments en in OZ ingepland voor 1.13 onder vlag van Utrecht.
