### ISSUE TITLE
PBAC op attribuut niveau

### ISSUE THREAD

**Issue by lstrijbosch** [generiekzaakafhandelcomponent/gzac-issues#38]
## Doel
De security/privacy verbeteren door te zorgen dat alleen de case data over de lijn gaat die ook echt getoond wordt (of nodig is) in het front-end. Op dit moment gaat nog bij iedere request de hele case JSON over de lijn, ook als er een PBAC tab configuratie is die een deel van de case verbergt.

## Context / achtergrond
Een case bevat soms privacy gevoelige informatie die niet door alle gebruikers van de case gezien mag worden. Deze informatie is functioneel wel relevant, denk bijvoorbeeld aan commentaar rondom een besluitvormingsproces dat vastgelegd wordt, maar tot op een zeker moment voor bepaalde gebruikers nog afgeschermd moet worden omdat het nog niet definitief is. Een ander voorbeeld is het vastleggen van enkele HR gegevens die functioneel relevant zijn voor de business logica in de applicatie, maar voor de gebruikers niet inzichtelijk hoeven en mogen zijn. 

## Huidige situatie
Op dit moment is het mogelijk om als gebruiker met toegang tot de case de hele case JSON in te zien door de "developer tools" functionaliteit in de browser te gebruiken en een request/response te openen. Dit geldt voor:
- Een geopende case (detail view)
- Een case die in een lijst staat (case list)

PBAC staat alleen toe om op case niveau af te schermen. De PBAC tab configuratie verandert niets aan de data die over de lijn gaat.

## Uitgangspunten
- Alleen data over de lijn die benodigd is voor het front-end
- Toegang configureerbaar op attribuut niveau
- Privacy by design. Attributen staan standaard dicht, openzetten is een bewuste actie.
- Configuratie blijft beheersbaar, bijvoorbeeld door een object binnen de case JSON open te kunnen zetten (maar binnen het object wel één attribuut dicht te kunnen zetten).
- Alle case data beschikbaar in één JSON (voor rapportages)
- Wat een gebruiker mag zien is afhankelijk van:
   - Gebruikersrol
   - Informatie van buiten de case (backend systeem via API)
   - Case data, bijvoorbeeld case status/fase.

## Denkrichting mogelijk oplossing
- In de case JSON: bij een attribuut een nieuwe optie pbac=true
- Voor attributen met pbac=true valideer tegen een pbac configuratie file
- Voor attributen met pbac=false of de optie ontbreekt, geef niks terug (privacy by design)
- De case JSON die teruggegeven wordt bevat alleen de vrijgegeven attributen.
- Feature flag om breaking change te voorkomen?

## Andere opmerkingen
Hoe gaat dit samenwerken met de tab policy die nu onderdeel is van PBAC?

**Comment by ThomasMinkeRitense** [comment]
@lstrijbosch met de implementatie van de dossier widgets en het verhuizen van gevoelige data buiten het document, kunnen we dit issue sluiten?

**Comment by lstrijbosch** [comment]
@ThomasMinkeRitense Ja, lijkt me prima deze te sluiten.
