### ISSUE TITLE
Beheerscherm voor het inzien van foutmeldingen

### ISSUE THREAD

**Issue by SjorsDriessen** [generiekzaakafhandelcomponent/gzac-issues#42]
## Doel
Als beheerder wil ik actief en passief inzicht in de gebruiksstatus en mogelijke foutmeldingen die optreden in de applicatie op gebied van processen en integraties, zodat ik adequaat kan handelen bij verstoringen. 
## Context / achtergrond
Doelgroep is een applicatiebeheerder die zoveel mogelijk volgens het no-code principe beheert, en dus de UI als ‘thuisbasis’ heeft.

- Het GZAC heeft geen optie om meldingen die in de console verschijnen ook in de UI weer te geven. Gerelateerd item: https://github.com/generiekzaakafhandelcomponent/roadmap-items/issues/37
- Het GZAC heeft geen integrale UI waarin de beheerder toegang krijgt tot een monitoringspagina om te zien wat de status van de actieve processen en plugins is.
- Het GZAC heeft geen optie om beheerders actief te notificeren, bijvoorbeeld per mail, wanneer er verstoringen optreden.
## Wat moet er gebeuren - wat is er nog niet en hebben we wel nodig?
De creatie van een dashboard waarop deze metrics weergegeven worden, gevuld met de requirements die bij beheerders worden opgehaald.
## Wat is het eindresultaat?
Direct inzicht in de status van de applicatie, processen en haar plugins, toegang tot een foutmeldingen log, actieve visuele notificaties bij problemen.
## Wat valt er buiten scope?
Er wordt een demarcatielijn getrokken tussen metrics die een PaaS-leverancier moet inzien om het product te kunnen leveren en metrics die een beheerder wil inzien om met vertrouwen te beheren. De PaaS-metrics vallen in deze story buiten scope.
## Impact - hoeveel inspanning kost dit? 
Inschatting door PO: S/M/L/XL  
Inschatting door SA: S/M/L/XL

**Comment by ThomasMinkeRitense** [comment]
Wellicht niet in scope maar wel gerelateerd: het (instelbaar?) verbergen van complexe foutmeldingen voor eindgebruikers.

**Comment by SjorsDriessen** [comment]
Dit lijkt mij inderdaad een goede aanvulling. Onder eindgebruiker versta ik in dit geval dan niet de beheerder, maar bijv. de zaakbehandelaar.

**Comment by ThomasMinkeRitense** [comment]
Eens, zo was hij ook bedoeld. In ieder geval verbergen voor degene die er toch niets mee kunnen. Aan de andere kant: een niet-goed-werkende omgeving zonder foutmelding is ook niet duidelijk voor de zaakbehandelaar.
