### ISSUE TITLE
Prefill and hide document metadata fields

### ISSUE THREAD

**Issue by ThomasMinkeRitense** [generiekzaakafhandelcomponent/gzac-issues#57]
## Why
*Why do we need this feature?*

- **Problem Statement**: What problem does this feature solve? What are the underlying pain points that make this feature necessary? 
This feature improves the user experience when uploading a document and filling in the required metadata fields. When a case handle has to upload a lot of files, filling in the metadata for each individual file can take a lot of time. The time needed can be reduced by configuring which fields should be filled in by the case handler, and which fields have a default or fixed value.
- **Value Proposition**: How will this feature add value to the users or the product? Why is it important to solve this problem?
This feature adds value because it reduces the time needed by the case handler to upload documents.

## How
*How do we envision this feature working?*

- **Guiding Principles**: What are the guiding principles or criteria for this feature? Consider user experience, design consistency, and alignment with the project's goals.
Guiding principle: don't ask the user for input while they shouldn't have a choice. 
- **Key Use Cases**: What are the primary scenarios in which this feature will be used? Describe the user journey and how this feature fits into it.
See above.

## What
*What needs to be done to implement this feature?*

- **Feature Description**: Provide a detailed description of the feature. What are the main components or elements?
The system administrator is able to configure default values for each of the document metadata fields. Per field, the system admin can configure if the field should be open to fill in, should have a default value, should be editable and should be visible.
- **Requirements**: List any specific requirements or constraints. Consider technical, design, or performance requirements.
The metadata field configuration should be configurable per case-type. The configuration should be auto-deployable and should be part of the case definition import and export.
- **Acceptance Criteria**: Define the acceptance criteria for this feature. What conditions must be met for this feature to be considered complete?
See above.

## Additional Context
- **Stakeholders**: Who are the key stakeholders or contributors for this feature?
- **References**: Include any relevant links, documents, or resources that provide additional context or support for this feature.
- **Potential Challenges**: Identify any potential challenges or obstacles that might arise during the implementation of this feature.

---

**Comment by ThomasMinkeRitense** [comment]
@AntonVissers

**Comment by erwinvdh** [comment]
@ThomasMinkeRitense Is it possible to make the prefilled data depending on user input? For example: 

- a use records the decision (besluit) 'aanvraag toegekent' in a user task
- next de the user uploads the related document (beschikking)
- the document meta data field documenttype is prefilled with the documenttype 'toekenningsbeschikking'

- a use records the decision (besluit) 'aanvraag afgewezen' in a user task
- next de the user uploads the related document (beschikking)
- the document meta data field documenttype is prefilled with the documenttype 'afwijzingsbeschikking'

**Comment by theo-ritense** [comment]
@ThomasMinkeRitense 
Extending the request by @erwinvdh :
We would like to be able to have the metadata (including the documenttype) be determined via value-resolvers or similar structure, so that different user tasks within the same case/process can use uploads with different prefilled metadata.

**Comment by ThomasMinkeRitense** [comment]
Please consider the option of shipping a v1 without autodeployment/import/export first.

**Comment by ThomasMinkeRitense** [comment]
Additional request: in case a document is uploaded from a task form, I'd like to use the task form data as document metadata. So instead of filling in the metadata after uploading, I'd like to use the data I've filled in before uploading.

**Comment by ThomasMinkeRitense** [comment]
Additional request: re-add dropzone
