### ISSUE TITLE
Aanvullende informatie op taakkaarten

### ISSUE THREAD

**Issue by lstrijbosch** [generiekzaakafhandelcomponent/gzac-issues#58]
## Waarom
*Waarom hebben we deze feature nodig?*

- **Probleemstelling**: De taakkaarten op een dossier zijn niet altijd duidelijk genoeg. Een gebruiker ziet taken (die niet van hem zijn), maar weet niet wie de taken gaan oppakken of voor welk moment. Extra context kan hier helpen, bijvoorbeeld "Welke rol binnen dit dossier gaat de taak oppakken" , en ook "Voor welk moment/gebeurtenis moet deze taak afgerond zijn". 
- **Waardepropositie**: Gebruikers krijgen hierdoor meer inzicht in het proces. Zeker bij lang lopende of complexere processen kan dit helpen voor een prettiger gebruikerservaring.

## Hoe
*Hoe zien we deze feature werken?*

- **Leidende Principes**: De extra informatie kan op één of meerdere regels op de kaart getoond te worden, als subtitels onder de taaknaam. Het belangrijkst is dat deze informatie op de kaartjes op de dossier-view (detail pagina) getoond worden. Deze subtitles de lijst hebben zou mooi zijn, maar in eerste instantie niet noodzakelijk. De informatie ligt vast per taak-definitie en is statisch, het is in feite extra tekst die op alle taken van dat type mag verschijnen.
- **Belangrijke Gebruiksscenario's**: Een gebruiker logt in en klikt op een dossier. Er staan een aantal taken, een taakkaartje bevat de informatie:
  - Taak naam, bijvoorbeeld "Provide Project Proposal"
  - Taak deadline text, bijvoorbeeld "Required before Kick-off review"
  - Taak target role, bijvoorbeeld "Student" (dus niet de persoon, maar de rol)

  Voor taken van de gebruiker zelf hoeft de rol niet getoond te worden (die staan al onder My Tasks).

## Wat
*Wat moet er gedaan worden om deze feature te implementeren?*

- **Functiebeschrijving**: Één of meer teksten (subtitles) op een kaart (minimaal 2 moet mogelijk zijn), te tonen als regels op een taakkaart.
- **Vereisten**: 
- **Acceptatiecriteria**: 
  - Mogelijkheid deze teksten in te richten bij een taak definitie
  - Teksten worden getoond op taakkaarten op dossier
  - (nice to have) Teksten beschikbaar als kolommen in de taaklijst

## Aanvullende Context
- **Belanghebbenden**: Al onze gebruikers: studenten, begeleiders, administratief personeel (werken samen aan één dossier).
- **Referenties**: Screenshot aan te leveren op aanvraag (hoe wij dit nu gebouwd hebben).
- **Potentiële Uitdagingen**: De tekst kan te lang zijn voor het kaartje. (afkorten met ...)

**Comment by ThomasMinkeRitense** [comment]
Wordt gereleased in 12.6.0.
