### ISSUE TITLE
Back knop van de browser logt me uit

### ISSUE THREAD

**Issue by Frits-Ritense** [generiekzaakafhandelcomponent/gzac-issues#72]
## Verwacht gedrag
*Wanneer ik vanaf het Dossierlijstscherm in een Dossier ga in GZAC en daarna op de back knop van de browser klik dat ik dan het lijstscherm weer te zien krijg.*

## Huidig gedrag
*Wanneer ik nu vanaf het lijstscherm een dossier open en daarna op de back knop van de browser klik dan wordt mijn dossierweergave ververst. Wanneer ik nog een keer op de back knop van de browser klik wordt ik uitgelogd.*

## Mogelijke oplossing (optioneel)
*...*

## Stappen om te reproduceren
*Geef een duidelijke reeks stappen om deze bug te reproduceren.*
*Voeg code toe om te reproduceren, indien relevant*
1. Open een dossier detail pagina
2. Klik op de back knop van de browser
3. Klik nogmaals op de back knop van de browser

**Comment by Tom-Ritense** [comment]
👍

**Comment by erik-ritense** [comment]
👍
